// JR Premium Client Links + status UI v6
(function(){
 const clean=s=>String(s||'').trim();
 const slugify=s=>clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' ').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 const prettyPath=x=>'/timelines/'+slugify(x?.couple_name||'wedding');
 const months={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11};
 function parseDate(s){s=clean(s).replace(/(\d)(st|nd|rd|th)\b/gi,'$1');let d=new Date(s);return isNaN(d)?null:d}
 function statusFromDate(d){if(!d||isNaN(d))return{label:'DATE TBD',kind:'tbd'};const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate());if(a>b)return{label:'WEDDING COMPLETED',kind:'done'};if(+a===+b)return{label:'LIVE · WEDDING DAY',kind:'today'};return{label:'UPCOMING',kind:'upcoming'}}
 function statusFor(x){return statusFromDate(parseDate(x?.wedding_date))}
 function badgeStyle(k){return k==='done'?'background:#fff1f0;color:#a13a32;border:1px solid #e8b9b5;':k==='today'?'background:#eef9f2;color:#267a49;border:1px solid #afd7bd;':k==='upcoming'?'background:#fff6e8;color:#a56512;border:1px solid #ebcf9f;':'background:#f4f2ef;color:#756f68;border:1px solid #ded8cf;'}
 function dashboardDate(row){const h=clean(row.closest('.month')?.querySelector('.monthHead h2')?.textContent),m=h.match(/^([A-Za-z]+)\s+(\d{4})$/),day=parseInt(clean(row.querySelector('.datebox')?.childNodes[0]?.textContent).replace(/\D/g,''),10);if(!m||!day)return null;return new Date(+m[2],months[m[1].toLowerCase()],day,12)}
 function decorateDashboard(){document.querySelectorAll('.wedding').forEach(row=>{const s=statusFromDate(dashboardDate(row));let tag=row.querySelector('.jrWeddingStatus');if(!tag){tag=document.createElement('span');tag.className='jrWeddingStatus';row.querySelector('.couple')?.appendChild(tag)}if(tag){tag.textContent=s.label;tag.style.cssText='display:table;margin-top:8px;padding:5px 8px;border-radius:999px;font-family:Inter,-apple-system,sans-serif;font-size:8px;line-height:1;letter-spacing:.11em;font-weight:800;'+badgeStyle(s.kind)}})}
 function currentWedding(){if(typeof state!=='undefined'&&state&&state.couple_name)return state;return null}
 function copyPretty(x){if(!x?.couple_name)return false;const u=location.origin+prettyPath(x);navigator.clipboard?.writeText(u);prompt('Client link (copied):',u);return true}
 async function bySlug(slug){try{const r=await fetch(API+'?public_slug=eq.'+encodeURIComponent(slug)+'&select=*',{headers:headers()}),d=await r.json();return d[0]||null}catch(e){return null}}
 async function premiumClientLink(slug){let x=(typeof all!=='undefined'?all:[]).find(v=>v.public_slug===slug)||await bySlug(slug);if(!copyPretty(x)){const u=location.origin+'/?timeline='+slug;navigator.clipboard?.writeText(u);prompt('Client link (copied):',u)}}
 const basePublic=window.publicView;
 async function premiumPublicView(slug){await basePublic(slug);const x=await bySlug(slug);if(!x)return;const s=statusFor(x),badge=document.querySelector('.live');if(badge){badge.innerHTML='<span class="dot"></span> '+s.label;badge.style.cssText+=';'+badgeStyle(s.kind)}const foot=document.querySelector('.footer');if(foot)foot.innerHTML=foot.innerHTML.replace(/^LIVE TIMELINE/i,s.kind==='done'?'WEDDING COMPLETED':s.kind==='today'?'LIVE · WEDDING DAY':'UPCOMING TIMELINE')}
 function nameMatch(pathSlug,name){
   const a=pathSlug.split('-').filter(Boolean),b=slugify(name).split('-').filter(Boolean);
   if(slugify(name)===pathSlug)return true;
   const aliases={kate:['kate','kathryn','katherine','katie'],santi:['santi','santiago'],sam:['sam','samantha'],mike:['mike','michael'],chris:['chris','christopher']};
   return a.length>0&&a.every(t=>b.some(n=>n===t||n.startsWith(t)||t.startsWith(n)||(aliases[t]||[]).includes(n)));
 }
 async function resolvePretty(){const m=location.pathname.match(/^\/timelines\/([^/]+)\/?$/i);if(!m)return;document.getElementById('app').innerHTML='<div class="public"><div class="publicCard"><div class="muted">Loading wedding timeline…</div></div></div>';try{const r=await fetch(API+'?select=*',{headers:headers()}),rows=await r.json(),matches=(rows||[]).filter(v=>nameMatch(m[1],v.couple_name)),x=matches.length===1?matches[0]:matches.find(v=>slugify(v.couple_name)===m[1]);if(x?.public_slug){await premiumPublicView(x.public_slug);return}}catch(e){console.error('Pretty timeline resolve failed',e)}document.getElementById('app').innerHTML='<div class="public"><div class="publicCard"><h2>Timeline not found.</h2><p class="muted">Please contact Jonhy & Rose for the current wedding timeline link.</p></div></div>'}
 function intercept(e){const b=e.target.closest('button');if(!b)return;const t=clean(b.textContent);if(t==='Publish Timeline'){e.preventDefault();e.stopImmediatePropagation();const x=currentWedding();if(!x?.id||!x?.public_slug){alert('Save Online first');return}copyPretty(x)}else if(t==='Client Link'){const row=b.closest('.wedding');if(!row)return;e.preventDefault();e.stopImmediatePropagation();const name=clean(row.querySelector('.couple')?.childNodes[0]?.textContent),x=(typeof all!=='undefined'?all:[]).find(v=>clean(v.couple_name)===name);if(x)copyPretty(x)}}
 function install(){document.addEventListener('click',intercept,true);const app=document.getElementById('app');if(app)new MutationObserver(()=>requestAnimationFrame(decorateDashboard)).observe(app,{childList:true,subtree:true});setInterval(decorateDashboard,1200);if(location.pathname.match(/^\/timelines\//i))resolvePretty();else decorateDashboard()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();