// JR Premium Client Links + status UI v4
(function(){
 const clean=s=>String(s||'').trim();
 const slugify=s=>clean(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
 const prettyPath=x=>'/timeline/'+slugify(x?.couple_name||'wedding');
 const months={january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11};
 function parseDate(s){s=clean(s).replace(/(\d)(st|nd|rd|th)\b/gi,'$1');let d=new Date(s);return isNaN(d)?null:d}
 function statusFromDate(d){if(!d||isNaN(d))return{label:'DATE TBD',kind:'tbd'};const n=new Date(),a=new Date(n.getFullYear(),n.getMonth(),n.getDate()),b=new Date(d.getFullYear(),d.getMonth(),d.getDate());if(a>b)return{label:'WEDDING COMPLETED',kind:'done'};if(+a===+b)return{label:'LIVE · WEDDING DAY',kind:'today'};return{label:'UPCOMING',kind:'upcoming'}}
 function statusFor(x){return statusFromDate(parseDate(x?.wedding_date))}
 function badgeStyle(kind){if(kind==='done')return'background:#fff1f0;color:#a13a32;border:1px solid #e8b9b5;';if(kind==='today')return'background:#eef9f2;color:#267a49;border:1px solid #afd7bd;';if(kind==='upcoming')return'background:#fff6e8;color:#a56512;border:1px solid #ebcf9f;';return'background:#f4f2ef;color:#756f68;border:1px solid #ded8cf;'}
 function dashboardDate(row){const section=row.closest('.month'),head=clean(section?.querySelector('.monthHead h2')?.textContent),m=head.match(/^([A-Za-z]+)\s+(\d{4})$/),day=parseInt(clean(row.querySelector('.datebox')?.childNodes[0]?.textContent).replace(/\D/g,''),10);if(!m||!Number.isFinite(day))return null;const mon=months[m[1].toLowerCase()];return mon===undefined?null:new Date(+m[2],mon,day,12)}
 function decorateDashboard(){document.querySelectorAll('.wedding').forEach(row=>{const s=statusFromDate(dashboardDate(row));let tag=row.querySelector('.jrWeddingStatus');if(!tag){tag=document.createElement('span');tag.className='jrWeddingStatus';const couple=row.querySelector('.couple');if(couple)couple.appendChild(tag)}if(tag){tag.textContent=s.label;tag.style.cssText='display:table;margin-top:8px;padding:5px 8px;border-radius:999px;font-family:Inter,-apple-system,sans-serif;font-size:8px;line-height:1;letter-spacing:.11em;font-weight:800;'+badgeStyle(s.kind)}})}
 function findWedding(slug){return (window.state&&state.public_slug===slug&&state.couple_name)?state:(window.all||[]).find(v=>v.public_slug===slug)}
 function premiumClientLink(slug){const x=findWedding(slug);if(x?.couple_name){const u=location.origin+prettyPath(x);navigator.clipboard?.writeText(u);prompt('Client link (copied):',u);return}const u=location.origin+'/?timeline='+slug;navigator.clipboard?.writeText(u);prompt('Client link (copied):',u)}
 const basePublic=window.publicView;
 async function premiumPublicView(slug){await basePublic(slug);try{const r=await fetch(API+'?public_slug=eq.'+encodeURIComponent(slug)+'&select=*',{headers:headers()}),d=await r.json(),x=d[0];if(!x)return;const s=statusFor(x),badge=document.querySelector('.live');if(badge){badge.innerHTML='<span class="dot"></span> '+s.label;badge.style.cssText+=';'+badgeStyle(s.kind);const dot=badge.querySelector('.dot');if(dot){dot.style.background=s.kind==='done'?'#a13a32':s.kind==='today'?'#267a49':'#a56512';dot.style.boxShadow='none'}}const foot=document.querySelector('.footer');if(foot)foot.innerHTML=foot.innerHTML.replace(/^LIVE TIMELINE/i,s.kind==='done'?'WEDDING COMPLETED':s.kind==='today'?'LIVE · WEDDING DAY':'UPCOMING TIMELINE')}catch(e){console.error('JR status:',e)}}
 async function resolvePretty(){const m=location.pathname.match(/^\/timeline\/([^/]+)\/?$/i);if(!m)return;try{const r=await fetch(API+'?select=*',{headers:headers()}),rows=await r.json(),x=(rows||[]).find(v=>slugify(v.couple_name)===m[1]);if(x?.public_slug){await premiumPublicView(x.public_slug);return}}catch(e){console.error(e)}document.getElementById('app').innerHTML='<div class="public"><div class="publicCard"><h2>Timeline not found.</h2></div></div>'}
 function install(){window.clientLink=premiumClientLink;window.publicView=premiumPublicView;window.JRPremiumLinks={slugify,prettyPath,statusFor,decorateDashboard};const app=document.getElementById('app');if(app)new MutationObserver(()=>requestAnimationFrame(decorateDashboard)).observe(app,{childList:true,subtree:true});setInterval(decorateDashboard,1200);if(location.pathname.match(/^\/timeline\//i))resolvePretty();else decorateDashboard()}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();